INSERT INTO RESTAURANTE (ID, NOME) VALUES (1, 'Mc Donalds');
INSERT INTO RESTAURANTE (ID, NOME) VALUES (2, 'Subway');
INSERT INTO RESTAURANTE (ID, NOME) VALUES (3, 'Habibs');
INSERT INTO RESTAURANTE (ID, NOME) VALUES (4, 'Bobs');
INSERT INTO RESTAURANTE (ID, NOME) VALUES (5, 'Burguer King');

INSERT INTO RANKING (ID, RESTAURANTE_FK, QUANT_VOTOS) VALUES (1, '4', 3);
